# Generated by Django 3.2.9 on 2021-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20211111_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='age',
            field=models.CharField(default='0000000', max_length=12),
        ),
    ]
