# Generated by Django 3.2.9 on 2021-11-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_reservation_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='medicalpractitioner',
            field=models.CharField(default='0000000', max_length=122),
        ),
    ]
