# Generated by Django 3.2.9 on 2021-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_reservation_medicalpractitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seniorcitizen',
            field=models.CharField(default='0000000', max_length=122),
        ),
    ]
