# Generated by Django 3.2.9 on 2021-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_reservation_seniorcitizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seniorcitizen',
            field=models.CharField(max_length=122),
        ),
    ]
