# Generated by Django 3.2.9 on 2021-11-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_reservation_seniorcitizen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seniorcitizen',
        ),
    ]
