# Generated by Django 3.2.9 on 2021-11-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_reservation_seniorcitizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniorcitizen', models.CharField(default='0000000', max_length=122)),
            ],
        ),
    ]
