# Generated by Django 3.2.9 on 2021-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_reservation2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation2',
            name='seniorcitizen',
            field=models.CharField(default='0000000', max_length=122, null=True),
        ),
    ]
