# Generated by Django 3.2.9 on 2021-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_reservation2_seniorcitizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation2',
            name='trainno',
            field=models.CharField(default='0000000', max_length=122),
        ),
    ]
