# Generated by Django 3.2.9 on 2021-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_alter_reservation2_trainno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation2',
        ),
        migrations.AddField(
            model_name='reservation',
            name='classname',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='noofseat',
            field=models.CharField(default='0000000', max_length=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seniorcitizen',
            field=models.CharField(default='0000000', max_length=40),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stationfrom',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stationto',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trainname',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trainno',
            field=models.CharField(default='0000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='gender',
            field=models.CharField(default='0000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='medicalpractitioner',
            field=models.CharField(default='0000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
